#!/usr/bin/env python
"""Self-contained reproduction script — generated by vivarium-dashboard.

Run from anywhere with the workspace's virtualenv, e.g.:
    .venv/bin/python influenza-sego2022.py

Figures are written to:  reports/notebooks/figures
Set RERUN = False (below) to render the committed runs.db without re-simulating.
"""
import os as _os
import sys as _sys

# YAML / study text is UTF-8; force UTF-8 mode so file reads don't depend on the
# shell locale (a bare-CLI run under an ASCII locale otherwise crashes on non-ASCII).
if _os.environ.get("PYTHONUTF8") != "1":
    _os.environ["PYTHONUTF8"] = "1"
    _os.execv(_sys.executable, [_sys.executable, *_sys.argv])


# # Influenza infection & immune response (Sego 2022 reproduction)
#
# _Investigation `influenza-sego2022` — coder reproduction notebook._
#
# **Question.** Can viva-cpm's native Cellular Potts engine reproduce, to quantitative figure
# match, the cellularized multiscale influenza-infection and immune-response
# model of Sego et al. 2022 — built on CompuCell3D's ViralInfectionVTM — at
# paper scale (Figs 3B, 5, 7)?
#
# A ground-up native reproduction of a published cellularized multiscale
# infection model (Sego, Mochan, Ermentrout & Glazier 2022, J. Theor. Biol.
# 532:110918), used as a rigor exercise for viva-cpm's CPM engine: can it
# reach quantitative figure match against a real, independently published
# spatial immunology model, using the authors' own CompuCell3D source as
# ground truth rather than just the paper's prose? The investigation was
# built up in stages — first establishing the specification and acceptance
# targets, then validating individual mechanisms at reduced scale, and
# finally assembling the full model for a capstone reproduction — so that
# reproducibility accrued cumulatively and each stage was independently
# reviewable.
#
# ---
#
# This notebook re-runs each study with the workspace's own process-bigraph protocol and renders its figures. The text states the **question and parameters** only — the figures produced by each run are the results. Set `RERUN = False` in the setup cell to render the committed `runs.db` without re-simulating.

"""Self-contained reproduction of this investigation.

Generated by vivarium-dashboard (notebook_export). Each study below is re-run
live with the workspace's own process-bigraph protocol and its figures are
rendered from the resulting runs.db.
"""
import os
import sys
from pathlib import Path

# Resolve the repository root robustly so this notebook runs from a fresh clone
# at ANY path with no setup (no env var, no path editing). Priority:
#   1. $VIVARIUM_REPO, if it points at a real directory;
#   2. walk up from the notebook's working directory for the repo markers
#      (a directory holding both 'workspace/' and 'pyproject.toml') — Jupyter
#      starts in the notebook's dir, so a committed notebook finds its own root;
#   3. the absolute path it was generated for (back-compat for old layouts);
#   4. the current working directory (last resort).
def _find_repo_root(_start):
    for _cand in (_start, *_start.parents):
        if (_cand / "workspace").is_dir() and (_cand / "pyproject.toml").is_file():
            return _cand
    return None

REPO = None
_env = os.environ.get("VIVARIUM_REPO")
if _env and Path(_env).is_dir():
    REPO = Path(_env)
if REPO is None:
    REPO = _find_repo_root(Path.cwd().resolve())
if REPO is None and Path('/home/runner/work/viva-cpm/viva-cpm').is_dir():
    REPO = Path('/home/runner/work/viva-cpm/viva-cpm')
if REPO is None:
    REPO = Path.cwd()
sys.path.insert(0, str(REPO))
# Composite specs use repo-root-relative paths (datasets, caches), and the
# workspace's runner/renderer assume cwd == repo root — so run from there.
os.chdir(REPO)

# Re-simulate from scratch? Set False to render the committed runs.db (fast).
RERUN = True

# --- standard process-bigraph protocol: register the workspace's Core ---
from viva_cpm_studies.core import build_core
core = build_core()

# --- imported from the repo this notebook was generated for ---


import contextlib as _contextlib, io as _io
@_contextlib.contextmanager
def quiet():
    """Silence the simulator's verbose per-step stdout so the notebook
    output stays readable (the figures below are the results)."""
    with _contextlib.redirect_stdout(_io.StringIO()):
        yield

import html as _htmlmod
def show_viz(_h, height=560):
    """Display a visualization's HTML in an isolated iframe.

    The figures embed their own scripts (e.g. Plotly); JupyterLab does not
    execute <script> tags from display(HTML(...)), so an iframe srcdoc is
    used instead — the browser runs the scripts inside the frame."""
    display(HTML(
        '<iframe srcdoc="{}" style="width:100%;height:{}px;border:0">'
        '</iframe>'.format(_htmlmod.escape(_h, quote=True), height)
    ))

import json as _json
def describe_spec(spec):
    """Print a composite spec's structure (parameters, processes, wiring)
    then the full editable dict. The spec is plain data — assign to any
    field (e.g. spec['state'][proc]['config'][...]) before building."""
    print("composite:", spec.get("name"))
    if spec.get("description"):
        print("description:", str(spec["description"]).strip())
    _params = spec.get("parameters") or {}
    if _params:
        print("\nparameters (filled into ${name} placeholders):")
        for _p, _pdef in _params.items():
            print(f"  {_p}: default={_pdef.get('default')!r}  type={_pdef.get('type')}")
    print("\nprocesses (node -> address):")
    for _node, _body in (spec.get("state") or {}).items():
        if not (isinstance(_body, dict) and _body.get("_type") == "process"):
            continue
        print(f"  {_node}  ->  {_body.get('address')}   interval={_body.get('interval')!r}")
        for _port in ("inputs", "outputs"):
            if _body.get(_port):
                print(f"      {_port} ports: {_body[_port]}")
    print("\nfull editable spec dict:")
    print(_json.dumps(spec, indent=2, default=str))

import base64 as _b64, pathlib as _pl
def _render_one(address, config, runs_db, study_yaml):
    """Generic figure renderer (no workspace render_study_viz.py):
    resolve an ``image:<relpath>`` visualization to displayable HTML,
    relative to the study directory."""
    addr = str(address or '')
    for _scheme in ('image:', 'file:', 'gif:', 'png:', 'svg:', 'jpg:', 'jpeg:'):
        if addr.startswith(_scheme):
            addr = addr[len(_scheme):]; break
    _p = _pl.Path(addr)
    if not _p.is_absolute():
        _p = _pl.Path(study_yaml).resolve().parent / _p
    if not _p.is_file():
        return f'<p style="color:#b91c1c">figure not found: {address}</p>'
    _suffix = _p.suffix.lower()
    if _suffix == '.svg':
        return _p.read_text(encoding='utf-8', errors='replace')
    if _suffix in ('.png', '.jpg', '.jpeg', '.gif', '.webp'):
        _mime = 'jpeg' if _suffix in ('.jpg', '.jpeg') else _suffix[1:]
        _data = _b64.b64encode(_p.read_bytes()).decode('ascii')
        return f'<img src="data:image/{_mime};base64,{_data}" style="max-width:100%"/>'
    if _suffix in ('.html', '.htm'):
        return _p.read_text(encoding='utf-8', errors='replace')
    return f'<p style="color:#6b7280">unsupported figure type: {address}</p>'

# ## Study: Parameter provenance & digitized Fig 3B/5/7 targets (`parameter-provenance`)
#
# **Question.** What is the authoritative, cited parameter set for reproducing Sego et al.
# 2022's cellularized influenza model (CompuCell3D ViralInfectionVTM), and
# where does the source disagree with the paper's own printed tables?
#
# **Objective.** Produce a single, cited parameter file and supporting provenance
# documentation that later increments can consume without re-deriving
# constants from the paper or source, and digitize the paper's Figs 3B, 5, 7
# into acceptance-band targets for the eventual capstone reproduction.
#
# **Hypothesis.** N/A — this is a documentation/provenance study, not a hypothesis-testing
# simulation. No hypothesis is evaluated here.
#
# **Purpose.** Documentation only — no simulation is run by this study. It establishes
# the parameter/spec authority that all later increments build on.
#
# **Claim.** The parameter authority for the influenza-sego2022 investigation is
# established and cited: params.yaml is sourced from the CC3D
# ViralInfectionVTM package and the paper's Tables 1-4, with every value
# traceable to one or the other, and figure-target acceptance bands exist for
# Figs 3B, 5, 7. This is a claim of DOCUMENTATION COMPLETENESS, not of
# reproduction — no simulation has been run against these targets.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `baseline` | `viva_cpm_studies.composites.influenza.epithelium` | 0 | patch_mm=0.1, seed=17 |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_cpm_studies.composites.influenza.epithelium`** — `spec_viva_cpm_studies_composites_influenza_epithelium` (a plain, editable dict)

# _composite spec file for `viva_cpm_studies.composites.influenza.epithelium` not found under `viva_cpm_studies/composites/` — skipped._

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: parameter-provenance ===
STUDY = 'parameter-provenance'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **Acceptance-band targets (Fig 3B)**

def _save_viz(study, slug, html):
    d = REPO / 'reports/notebooks/figures' / study
    d.mkdir(parents=True, exist_ok=True)
    out = d / (slug + '.html')
    out.write_text(html, encoding='utf-8')
    print('  wrote', out)


# Acceptance-band targets (Fig 3B)
_save_viz('parameter-provenance', 'Acceptance-band_targets_Fig_3B', _render_one('local:InfluenzaFig3BTargets', {}, RUNS_DB, STUDY_YAML))

# ## Study: Epithelial sheet baseline (`epithelial-sheet-baseline`)
#
# **Question.** Does a confluent tiling of epithelial (type H) cells, using the CC3D
# source-literal adhesion values (H-H=5.0, H-medium=25.0) and target volume
# (25 sites), hold stable under CPM relaxation at paper scale, and does the
# Rust engine step it fast enough for the eventual 2-week/~20160-MCS
# capstone run?
#
# **Objective.** Build the epithelial-sheet `load_world` spec (Task 1.1), instantiate and
# relax the CPM world (Task 1.2), and measure step throughput on the full
# 1mm^2 patch (Task 1.3). Wrap the geometry in a process-bigraph composite
# (`viva_cpm_studies.composites.influenza.epithelium`) so the
# dashboard can run a modest (0.1mm, 100-cell) live demo of the same
# substrate (Task 1.4, this study).
#
# **Hypothesis.** The confluent sheet holds: after relaxation every real cell (indices 1..N,
# excluding the medium placeholder at index 0) has volume close to its
# target of 25 sites, with none vanishing. Separately, 1mm^2 throughput
# comfortably clears the ~2.0 MCS/s floor required for the capstone's
# ~20160-step run to finish in a practical wall-clock time.
#
# **Purpose.** epithelial_sheet_substrate
#
# **Claim.** The confluent epithelial-only sheet is geometrically stable (mean cell
# volume ~25 sites, none vanished) and the Rust CPM engine steps the full
# 1mm^2 lattice at ~406-422 MCS/s, far above the throughput needed to make
# the eventual 2-week capstone run computationally tractable. This is a
# substrate-readiness claim, not a biological-reproduction claim.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `baseline` | `viva_cpm_studies.composites.influenza.epithelium` | 0 | patch_mm=0.1 |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_cpm_studies.composites.influenza.epithelium`** — `spec_viva_cpm_studies_composites_influenza_epithelium` (a plain, editable dict)

# _composite spec file for `viva_cpm_studies.composites.influenza.epithelium` not found under `viva_cpm_studies/composites/` — skipped._

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: epithelial-sheet-baseline ===
STUDY = 'epithelial-sheet-baseline'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **Spatial state — sheet relaxation (animated)**

# Spatial state — sheet relaxation (animated)
_save_viz('epithelial-sheet-baseline', 'Spatial_state_sheet_relaxation_animated', _render_one('local:InfluenzaSpatialSheet', {}, RUNS_DB, STUDY_YAML))

# **Confluent epithelial sheet**

# Confluent epithelial sheet
_save_viz('epithelial-sheet-baseline', 'Confluent_epithelial_sheet', _render_one('local:InfluenzaEpithelialSheet', {}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | Sheet holds confluent after relaxation | kind=mean_cell_volume_sites condition=epithelial-sheet-baseline stat=mean | op gt value 0 |
# | 1mm^2 throughput clears the perf-gate floor | kind=throughput_mcs_per_s condition=epithelial-sheet-baseline stat=min | op gt value 200.0 |

# ## Study: Virus field & stochastic H→I infection (`virus-field-infection`)
#
# **Question.** Does the extracellular virus field (source-cited diffusion coefficient and
# decay rate, secreted by InfectedReleasing cells) diffuse and decay as
# specified, and does a stochastic, field-driven H -> I infection transition
# spread a seeded lesion LOCALLY (new infections cluster near existing
# infected cells) rather than uniformly, with total cell population
# conserved?
#
# **Objective.** Wire the virus field (Task 2.1, `viva_cpm_studies/influenza/fields.py`) and
# the stochastic infection transition (Task 2.2,
# `viva_cpm_studies/influenza/transitions.py`) together over the Increment-1
# sheet, drive them for 60 updates from a small seeded lesion
# (`viva_cpm_studies/influenza/run.py::run_virus_infection`, Task 2.3), and
# report the measured spread/locality/null-control behavior from the
# integration test (`tests/test_influenza_virus_infection.py`). Wrap the
# same mechanism as a process-bigraph composite
# (`viva_cpm_studies.composites.influenza.viral_infection`, CPMProcess +
# InfectionProcess wired through `fates`) for the dashboard live demo (Task
# 2.4, this study) — measurements come from `run_virus_infection`, not the
# live-demo composite (see caveat and Task 2.3's report on why the two
# paths use independent RNG streams and are not bit-identical).
#
# **Hypothesis.** Layered on the Increment-1 confluent sheet: a virus field secreted by a
# small seeded lesion of InfectedReleasing (I) cells diffuses outward and
# decays; a stochastic H -> I transition (rate = g_hv * local mean field
# concentration) converts nearby Healthy (H) cells to Infected (I) over
# time, with new infections landing close to already-infected cells (within
# a few multiples of the field's own diffusion length) rather than
# scattered across the whole sheet, and n_H + n_I conserved every update.
#
# **Purpose.** virus_field_and_infection_transition
#
# **Claim.** The extracellular virus field diffuses and decays as specified, and a
# seeded lesion of infected cells spreads via a stochastic, virus-driven
# healthy-to-infected transition that stays local to existing infection,
# with total cell population conserved throughout. This validates the
# mechanism only — it is not a claim that any of Sego et al. 2022's
# quantitative figure targets are met; that reproduction verdict remains
# pending until the capstone increment.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `baseline` | `viva_cpm_studies.composites.influenza.viral_infection` | 0 | patch_mm=0.1, seed=17, init_infected_frac=0.05 |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_cpm_studies.composites.influenza.viral_infection`** — `spec_viva_cpm_studies_composites_influenza_viral_infection` (a plain, editable dict)

# _composite spec file for `viva_cpm_studies.composites.influenza.viral_infection` not found under `viva_cpm_studies/composites/` — skipped._

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: virus-field-infection ===
STUDY = 'virus-field-infection'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **Spatial state — infection spread (animated)**

# Spatial state — infection spread (animated)
_save_viz('virus-field-infection', 'Spatial_state_infection_spread_animated', _render_one('local:InfluenzaSpatialVirusField', {}, RUNS_DB, STUDY_YAML))

# **Virus field + local spread (animated)**

# Virus field + local spread (animated)
_save_viz('virus-field-infection', 'Virus_field_local_spread_animated', _render_one('local:InfluenzaVirusFieldScene', {}, RUNS_DB, STUDY_YAML))

# **Infection dynamics + locality**

# Infection dynamics + locality
_save_viz('virus-field-infection', 'Infection_dynamics_locality', _render_one('local:InfluenzaInfectionDynamics', {}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | Seeded lesion spreads over time (population conserved) | kind=n_I condition=virus-field-infection stat=delta | op gt value 0 |
# | New infections land closer to prior infection than random chance (locality) | kind=locality_null_ratio condition=virus-field-infection stat=mean | op lt value 0.75 |
# | No seed, no initial virus -> no infection (null control) | kind=n_I condition=virus-field-infection-null stat=max | op eq value 0 |

# ## Study: Type-I IFN field & cellular resistance (`ifn-resistance`)
#
# **Question.** Does a diffusing type-I IFN field, converted per-cell into a resistance
# scalar via the CC3D-source formula `resist = f_bar/(a_rf+f_bar)`, gate
# infected cells' virus secretion by `(1-resist)` strongly enough to
# measurably slow infection spread and reduce total virus versus the same
# seed/parameters with no IFN (Increment 2's unmodified path)?
#
# **Objective.** Wire the type-I IFN field (Task 3.2, `viva_cpm_studies/influenza/fields.py`
# `add_ifn_field`) and the pure per-cell resistance function (Task 3.3,
# `viva_cpm_studies/influenza/resistance.py::cell_resistance`) into a new
# driver, `run.run_virus_infection_with_ifn` (Task 3.3), alongside the
# unmodified Increment-2 `run_virus_infection`, and compare their per-update
# series (n_I, n_H, total_virus, plus `mean_resist` recorded only by the
# with-IFN driver) at identical seed/parameters (Task 3.3's integration test
# `tests/test_influenza_virus_infection.py::test_ifn_resistance_slows_spread_vs_no_ifn`
# and the fuller with/without series in Task 3.3's report). A minimal
# in-package figure (`viva_cpm_studies/influenza/viz.py::ifn_resistance_figure`,
# Task 3.4) renders both series side by side plus the mean_resist trajectory.
#
# **Hypothesis.** Layered on the Increment-2 virus field + infection transition: a type-I
# IFN field secreted by infected cells diffuses and decays; each infected
# cell's locally-sampled mean IFN drives a per-cell resistance scalar that
# throttles ITS OWN virus secretion for the next update. This should leave
# n_I lower and total_virus substantially lower than an identical no-IFN
# run at the same steps, while mean_resist stays strictly positive once IFN
# has had time to accumulate.
#
# **Purpose.** ifn_field_and_per_cell_resistance
#
# **Claim.** A type-I IFN field, converted per-cell into a resistance scalar, gates
# virus secretion and roughly halves total virus versus an identical
# no-IFN run — the study's primary, robust evidence. Infected-cell count
# moves the same protective direction but more weakly, becoming meaningful
# only later in the run. This validates the mechanism only; it is not a
# claim that Sego et al. 2022's quantitative figure targets are met, which
# remains pending.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `baseline` | `viva_cpm_studies.composites.influenza.viral_infection` | 0 | patch_mm=0.1, seed=17, init_infected_frac=0.05 |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_cpm_studies.composites.influenza.viral_infection`** — `spec_viva_cpm_studies_composites_influenza_viral_infection` (a plain, editable dict)

# _composite spec file for `viva_cpm_studies.composites.influenza.viral_infection` not found under `viva_cpm_studies/composites/` — skipped._

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: ifn-resistance ===
STUDY = 'ifn-resistance'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **Spatial state — IFN-gated infection (animated)**

# Spatial state — IFN-gated infection (animated)
_save_viz('ifn-resistance', 'Spatial_state_IFN-gated_infection_animated', _render_one('local:InfluenzaSpatialIfnResistance', {}, RUNS_DB, STUDY_YAML))

# **IFN + per-cell resistance**

# IFN + per-cell resistance
_save_viz('ifn-resistance', 'IFN_per-cell_resistance', _render_one('local:InfluenzaIfnResistance', {}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | IFN-gated resistance does not let spread outrun the no-IFN path (weak directional check) | kind=n_I_delta_vs_without_ifn condition=ifn-resistance stat=final | op le value 0 |
# | IFN-gated virus release leaves strictly less total virus (primary quantitative gate) | kind=total_virus_delta_vs_without_ifn condition=ifn-resistance stat=final | op lt value 0 |
# | Resistance gate actually engages (mean_resist > 0) | kind=mean_resist condition=ifn-resistance stat=final | op gt value 0.0 |

# ## Study: Epithelial death & Allee recovery (`epithelial-fate`)
#
# **Question.** Does wiring infection (H->I), infected death (I->D), and the cellularized
# Allee effect (H->D death / D->H recovery, both gated by local contact
# geometry) together produce a coherent epithelial-fate lifecycle -- a
# growing dead lesion, population conservation, and correct bidirectional
# Allee response (recovery for well-surrounded D cells, no recovery for
# poorly-surrounded ones) -- on top of the Increment 2/3 virus/infection/IFN
# path?
#
# **Objective.** Wire infected death (Task 4.2, `transitions.infected_death_step`) and the
# cellularized Allee effect (Task 4.3, `viva_cpm_studies/influenza/allee.py`)
# into a new driver, `run.run_epithelial_fate` (Task 4.3), alongside the
# unmodified Increment-2/3 infection + IFN-resistance path, and measure the
# resulting n_H/n_I/n_D series plus the diagnostic n_allee_death/
# n_allee_recovery counters (Task 4.3's integration tests
# `tests/test_influenza_allee.py::test_lesion_forms_dead_region_grows_over_time`,
# `::test_dead_cell_surrounded_by_uninfected_recovers`,
# `::test_dead_cell_surrounded_by_dying_does_not_recover`, and the fuller
# 200/500-step series in task-4.3-report.md). A minimal in-package figure
# (`viva_cpm_studies/influenza/viz.py::epithelial_fate_figure`, Task 4.4)
# renders the cell-type composition over time plus cumulative Allee event
# counts.
#
# **Hypothesis.** Layered on the Increment-2/3 virus field + infection + IFN-resistance
# path: infected cells die at rate `mu_i*(1-resist)` (I->D), and every H/D
# epithelial cell's local contact-surface composition (restricted to H/I/D
# neighbors) drives a stochastic Allee death (H->D, for H cells deeply
# embedded in dead tissue) or recovery (D->H, for D cells mostly surrounded
# by healthy tissue) rate. This should produce a growing, population-
# conserving dead lesion over time, with D cells embedded in healthy tissue
# recovering and D cells embedded in dying tissue never recovering -- while
# direct Allee death may be rare at reduced (0.3mm) scale given the
# source's b_h/theta asymmetry.
#
# **Purpose.** epithelial_fate_lifecycle
#
# **Claim.** Wiring infection, infected death, and the cellularized Allee effect
# together produces a coherent, population-conserving epithelial-fate
# lifecycle: a dead lesion grows, and dead cells surrounded by healthy
# tissue recover while those surrounded by dying tissue never do. This
# validates the mechanism only, not a reproduction of Sego et al. 2022's
# figure targets. Direct Allee death is honestly reported as rare at this
# scale, verified genuine rather than a wiring bug.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `baseline` | `viva_cpm_studies.composites.influenza.viral_infection` | 0 | patch_mm=0.1, seed=17, init_infected_frac=0.05 |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_cpm_studies.composites.influenza.viral_infection`** — `spec_viva_cpm_studies_composites_influenza_viral_infection` (a plain, editable dict)

# _composite spec file for `viva_cpm_studies.composites.influenza.viral_infection` not found under `viva_cpm_studies/composites/` — skipped._

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: epithelial-fate ===
STUDY = 'epithelial-fate'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **Spatial state — fate lifecycle (animated)**

# Spatial state — fate lifecycle (animated)
_save_viz('epithelial-fate', 'Spatial_state_fate_lifecycle_animated', _render_one('local:InfluenzaSpatialEpithelialFate', {}, RUNS_DB, STUDY_YAML))

# **Epithelial-fate lifecycle**

# Epithelial-fate lifecycle
_save_viz('epithelial-fate', 'Epithelial-fate_lifecycle', _render_one('local:InfluenzaEpithelialFate', {}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | Epithelial-fate lifecycle forms a growing dead lesion, population conserved | kind=n_D_final condition=epithelial-fate stat=final | op gt value 0 |
# | Dead cell fully surrounded by healthy tissue recovers (D->H) | kind=recovers_within_500_draws condition=epithelial-fate stat=final | op eq value True |
# | Dead cell surrounded by dying tissue never recovers (negative control) | kind=recovery_rate_over_500_draws condition=epithelial-fate stat=max | op eq value 0.0 |

# ## Study: Immune response at tissue scale (`immune-response`)
#
# **Question.** Do the innate and adaptive immune mechanisms — macrophage chemotaxis, the
# macrophage-released chemokine and IL-10 signalling field, and NK/CD8
# cytotoxic localization — compose into a coherent immune response at a
# representative tissue scale (a roughly 900-cell epithelial sheet)?
#
# **Objective.** Run the full immune layer (macrophage, NK, CD8+ T cells) on a ~900-cell
# epithelial sheet seeded with an infected patch, and confirm the immune cells
# chemotax toward the infection and cluster against the sheet.
#
# **Hypothesis.** Running the full immune layer on a tissue-scale sheet will show macrophage,
# NK, and CD8+ T cells chemotaxing toward an infected patch and clustering
# against the sheet, with contact-killing field-magnitude-limited at full scale.
#
# **Claim.** The immune mechanisms (macrophage/NK/CD8 chemotaxis + chemokine signalling)
# compose and localise toward infection at tissue scale. Contact-killing at full
# scale remains the documented field-magnitude calibration gap (quantified in the
# capstone) -- this is a MECHANISM result, not a Fig-3B/5/7 reproduction claim.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `baseline` | `viva_cpm_studies.composites.influenza.cytotoxic_immunity` | 0 | patch_mm=0.1, seed=17, init_infected_frac=0.05 |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_cpm_studies.composites.influenza.cytotoxic_immunity`** — `spec_viva_cpm_studies_composites_influenza_cytotoxic_immunity` (a plain, editable dict)

# _composite spec file for `viva_cpm_studies.composites.influenza.cytotoxic_immunity` not found under `viva_cpm_studies/composites/` — skipped._

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: immune-response ===
STUDY = 'immune-response'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **InfluenzaSpatialImmune**

# InfluenzaSpatialImmune
_save_viz('immune-response', 'InfluenzaSpatialImmune', _render_one('', {}, RUNS_DB, STUDY_YAML))

# ## Study: Global Price-2015 ODE coupling (`global-coupling`)
#
# **Question.** Does coupling the Price (2015)-derived global immune ODE (10 systemic
# species) bidirectionally to the spatial CPM patch — dynamic sig_1
# feedback, ODE-driven recruitment, and a well-mixed nearby-population
# killing term — resolve the three stubs carried since Increments 5-7 into
# mechanisms that are individually correct and source-faithful, and do the
# resulting coupling magnitudes already reconcile at this reduced-scale
# patch, or is that an open Increment-9 calibration item?
#
# **Objective.** Wire `price_ode.GlobalODE` (Task 8.1, the hybrid 10-species integrator,
# discrepancy #9) into `run.run_global_coupling`'s per-MCS loop: spatial->
# ODE aggregate push (Task 8.2), ODE->spatial dynamic sig_1 feedback (Task
# 8.3, discrepancy #11), ODE-driven recruitment (Task 8.4, discrepancy
# #12), and NK/CD8 LOCAL+NEARBY cytotoxic killing (Task 8.5). Measure sig_1's
# dynamic range vs the retired static stub, recruitment inflow/outflow
# rates and population trajectories (default vs boosted eta), and whether
# the nearby-killing term fires via natural recruitment buildup vs a
# documented test-seam override
# (`tests/test_influenza_price_ode.py`, `tests/test_influenza_recruitment.py`,
# `tests/test_influenza_killing.py`, task-8.1 through task-8.5-report.md).
# A minimal in-package figure (`viva_cpm_studies/influenza/viz.py::
# global_coupling_figure`, Task 8.6) renders the systemic ODE species
# (T/X/A/P) and the spatial aggregates (I/M/K/E) plus dynamic sig_1 over
# MCS.
#
# **Hypothesis.** Integrating the 10 systemic ODE species once per MCS, fed by the spatial
# model's cell counts/field integrals and feeding back a dynamic sig_1 plus
# ODE-driven recruitment plus a nearby-population killing term, will
# produce mechanisms that are each individually verifiable as correct
# (dynamic sig_1 tracks TNF/dead count; recruitment shows the source's
# documented CD8-no-baseline asymmetry; nearby-killing clears infected
# cells given a sufficient nearby population) — but at this driver's small
# reduced-scale default (tiny eta), the resulting coupling magnitudes may
# not yet be large enough to produce an observable effect within a
# feasible step budget, which should be reported honestly as a
# calibration gap deferred to Increment 9, not concealed by tuning
# constants to force a better-looking number.
#
# **Purpose.** hybrid_price2015_global_ode_bidirectional_coupling
#
# **Claim.** The hybrid global immune ODE integrates stably each step and couples
# bidirectionally with the spatial model, resolving three previously-
# stubbed mechanisms — dynamic IL-10/chemokine signaling, ODE-driven
# recruitment, and a nearby-population killing term — each individually
# verified correct. At this reduced-scale patch, none of these mechanisms'
# magnitudes yet reconcile with the values replaced or reach an observable
# effect: a field-versus-ODE unit-scale calibration gap, reported honestly
# and deferred rather than tuned away.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `baseline` | `viva_cpm_studies.composites.influenza.systemic_ode` | 0 | chemotaxis_v_macro=5000.0, chemotaxis_v_nk=500000.0, chemotaxis_v_cd8=1000000.0, seed=17 |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_cpm_studies.composites.influenza.systemic_ode`** — `spec_viva_cpm_studies_composites_influenza_systemic_ode` (a plain, editable dict)

# _composite spec file for `viva_cpm_studies.composites.influenza.systemic_ode` not found under `viva_cpm_studies/composites/` — skipped._

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: global-coupling ===
STUDY = 'global-coupling'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **Spatial state — global immune scene (animated)**

# Spatial state — global immune scene (animated)
_save_viz('global-coupling', 'Spatial_state_global_immune_scene_animated', _render_one('local:InfluenzaSpatialGlobalCoupling', {}, RUNS_DB, STUDY_YAML))

# **Hybrid global ODE coupling**

# Hybrid global ODE coupling
_save_viz('global-coupling', 'Hybrid_global_ODE_coupling', _render_one('local:InfluenzaGlobalCoupling', {}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | GlobalODE integrates the 10 systemic species stably over a run | kind=ode_states_finite_and_stable condition=global-coupling-ode-stability stat=final | op eq value True |
# | Dynamic sig_1 differs from and replaces the static stub | kind=sig_1_dynamic_monotone_and_differs_from_stub condition=dynamic-sig1-vs-stub stat=final | op eq value True |
# | CD8+ recruitment inflow is APC-driven with no homeostatic baseline | kind=cd8_recruitment_is_apc_driven_asymmetry_preserved condition=cd8-no-baseline-recruitment stat=final | op eq value True |
# | Nearby-population killing clears infected cells given a sufficient nearby population | kind=n_infected_final_lower_with_nearby_surrogate_present condition=nearby-killing-on-vs-off stat=final | op lt value n_infected_final[K_nb=E_nb=0 control] |
# | DH-input fix -- dead-from-infected cells do not inflate the dead-from-healthy ODE input | kind=dh_input_zero_regardless_of_killing condition=dh-input-fix stat=final | op eq value True |
# | global_coupling_figure renders a non-vacuous 2-panel mechanism figure | kind=figure_axes_and_data_match_driver_output condition=global-coupling-figure-non-vacuous stat=final | op eq value True |

# ## Study: Reproduction — Fig 3B (time series vs ODE) (`repro-fig3b`)
#
# **Question.** Does `run.repro_fig3b` (Task 9.2) correctly assemble a seeded ensemble of
# `run.run_full_model` (Task 9.1) over the Sego-2022 Fig-3B scenario, map
# its output onto `targets/fig3b.json`'s exact observable keys, and evaluate
# the ensemble mean against the digitized Fig-3B acceptance bands
# (`bands.evaluate_study`) -- and, honestly, does a REDUCED-scale ensemble
# (the only scale a fast CI test can run) land in-band, or does it mostly
# expose the reduced population/duration's mismatch with the paper-scale
# bands rather than any mechanism defect?
#
# **Objective.** Implement `run.repro_fig3b(*, replicas=3, cells_per_side=35, steps=240,
# seed0=0) -> dict` (Task 9.2): loop `replicas` seeds through
# `run.run_full_model(cells_per_side=cells_per_side, steps=steps,
# seed=seed0+i, init_infection_frac=0.05)`; map each run's
# `counts`/`fields`/`ode` sections onto `targets/fig3b.json`'s exact
# observable keys (`_FIG3B_OBSERVABLE_MAP`); ensemble-mean via
# `bands.aggregate_replicas`; evaluate via `bands.evaluate_study(ensemble,
# "fig3b")`. Add `tests/test_influenza_full_model.py::
# test_repro_fig3b_runs_and_evaluates_bands` (reduced: `replicas=2,
# cells_per_side=15, steps=20`) asserting the ensemble/band_eval dict is
# well-formed and the uninfected series is non-vacuous (declines under
# infection) -- NOT that the bands pass, since reduced scale is not
# expected to. Run that same reduced config directly (not the pytest
# assertions alone) to report the actual per-observable band_eval numbers
# in this study honestly.
#
# **Hypothesis.** `run.repro_fig3b` correctly wires the ensemble-and-band-evaluation
# machinery: it runs `replicas` seeded `run_full_model` calls, maps every
# mapped observable's series onto the fig3b target's keys, ensemble-means
# them, and produces a well-formed `band_eval` dict. At REDUCED scale
# (small `cells_per_side`, few `replicas`, short `steps` -- all needed to
# keep the added pytest test fast), the ensemble is NOT expected to land
# in-band against bands digitized from a 1225-cell, 50-replica, ~3.5-day
# paper-scale ensemble; any near-miss or in-band result at reduced scale
# should be reported as what it is (a coincidence of a widened `soft` band
# and/or an early-timepoint value that happens to still be small), not
# oversold as reproduction evidence.
#
# **Purpose.** full_model_ensemble_vs_fig3b_acceptance_bands
#
# **Claim.** `repro_fig3b` correctly assembles a seeded ensemble of the full model
# over the Fig-3B scenario and evaluates it against the digitized
# acceptance bands, producing a well-formed result. Fig-3B is not
# reproduced at the reduced scale a fast test affords: none of the twelve
# observables land in-band at every checkpoint, a scale-and-duration
# mismatch rather than evidence of a mechanism defect. A paper-scale
# ensemble is required before any reproduction verdict.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `baseline` | `viva_cpm_studies.composites.influenza.full_model` | 20 | replicas=2, cells_per_side=15, seed0=0 |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_cpm_studies.composites.influenza.full_model`** — `spec_viva_cpm_studies_composites_influenza_full_model` (a plain, editable dict)

# _composite spec file for `viva_cpm_studies.composites.influenza.full_model` not found under `viva_cpm_studies/composites/` — skipped._

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: repro-fig3b ===
STUDY = 'repro-fig3b'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **Spatial state — full model (animated)**

# Spatial state — full model (animated)
_save_viz('repro-fig3b', 'Spatial_state_full_model_animated', _render_one('local:InfluenzaSpatialReproFig3B', {}, RUNS_DB, STUDY_YAML))

# **Fig-3B reproduction — ensemble vs acceptance band**

# Fig-3B reproduction — ensemble vs acceptance band
_save_viz('repro-fig3b', 'Fig-3B_reproduction_ensemble_vs_acceptance_band', _render_one('local:InfluenzaReproFig3B', {}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | repro_fig3b runs and returns a well-formed ensemble/band evaluation | kind=repro_fig3b_wellformed_and_uninfected_nonincreasing condition=repro-fig3b-reduced-scale stat=final | op eq value True |

# ## Study: Reproduction — Fig 5 (viral-load sweep) (`repro-fig5-viral-load`)
#
# **Question.** Does `run.repro_fig5` (Task 9.3) correctly sweep `run.run_full_model`
# (Task 9.1) over Sego-2022 Fig-5's initial-viral-load scenarios, evaluate
# EACH load against ONLY that load's own fig5.json band subset (never the
# unfiltered, multi-scenario list), and reproduce the paper's central
# monotone, threshold-like dose-response direction -- and, honestly, does a
# REDUCED-scale sweep (the only scale a fast CI test can run) show that
# direction even though it cannot match the digitized bands' absolute
# magnitudes at paper scale?
#
# **Objective.** Implement `run.repro_fig5(*, loads=(1,10,100,1000,10000), replicas=3,
# cells_per_side=35, steps=240, seed0=0) -> dict` (Task 9.3): for each
# `load`, loop `replicas` seeds through `run.run_full_model(
# cells_per_side=cells_per_side, steps=steps, seed=seed0+load_idx*replicas+r,
# init_viral_load=load, init_infection_frac=None)`; map each run's
# `counts`/`fields`/`ode` sections onto `targets/fig5.json`'s exact 4
# observable keys (`_FIG5_OBSERVABLE_MAP`); ensemble-mean via
# `bands.aggregate_replicas`; filter that load's own band subset from
# fig5.json's multi-scenario observable lists (`_fig5_target_subset`,
# raising `ValueError` rather than silently mixing scenarios if a load has
# no matching entries); evaluate via `_evaluate_fig5_subset`. Add
# `tests/test_influenza_full_model.py::test_repro_fig5_viral_load_sweep`
# (reduced: `loads=(1,10000), replicas=1, cells_per_side=12, steps=15`)
# asserting the by_load dict has exactly the tested loads as keys, the
# monotone dose-response holds (`uninfected_final_frac(10000) <=
# uninfected_final_frac(1) + 1e-9`), and `band_eval` is present -- NOT
# that the bands pass, since reduced scale is not expected to. Run that
# same reduced config directly (not the pytest assertions alone) to report
# the actual per-load, per-observable band_eval numbers in this study
# honestly.
#
# **Hypothesis.** `run.repro_fig5` correctly wires the per-load ensemble-and-scenario-
# filtered-band-evaluation machinery: for each tested load it runs
# `replicas` seeded `run_full_model` calls with a uniform virus-field IC,
# maps every observable onto fig5's keys, ensemble-means them, filters
# fig5.json's observable lists down to that load's own scenario subset
# (the guard), and produces a well-formed per-load `band_eval`. At REDUCED
# scale (few loads/replicas, a small population, a short duration -- all
# needed to keep the added pytest test fast), the ensemble is NOT expected
# to land in-band against bands digitized from a 10000-cell, 50-replica,
# 15-day paper-scale ensemble, but the MONOTONE dose-response direction
# (higher initial viral load -> not-more surviving uninfected fraction)
# should still hold, since it is a qualitative mechanism check independent
# of population/time scale; any near-miss or in-band result at reduced
# scale should be reported as what it is (a coincidence of a wide,
# paper-reported-high-spread band and/or a near-instant collapse that
# happens to land inside it), not oversold as reproduction evidence.
#
# **Purpose.** full_model_viral_load_sweep_vs_fig5_acceptance_bands
#
# **Claim.** `repro_fig5` is wired correctly: it sweeps a seeded ensemble of the full
# model across Fig-5's viral-load scenarios and evaluates each load
# against only its own acceptance-band subset. This study does not claim
# Fig-5 is reproduced — at reduced population and run duration, per-load
# band containment fails, though the monotone dose-response direction
# (higher initial viral load, fewer surviving uninfected cells) holds. A
# paper-scale ensemble is required before any reproduction verdict.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `baseline` | `viva_cpm_studies.composites.influenza.full_model` | 15 | loads=[1, 10000], replicas=1, cells_per_side=12, seed0=0 |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_cpm_studies.composites.influenza.full_model`** — `spec_viva_cpm_studies_composites_influenza_full_model` (a plain, editable dict)

# _composite spec file for `viva_cpm_studies.composites.influenza.full_model` not found under `viva_cpm_studies/composites/` — skipped._

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: repro-fig5-viral-load ===
STUDY = 'repro-fig5-viral-load'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **Spatial state — full model (animated)**

# Spatial state — full model (animated)
_save_viz('repro-fig5-viral-load', 'Spatial_state_full_model_animated', _render_one('local:InfluenzaSpatialReproFig5', {}, RUNS_DB, STUDY_YAML))

# **Fig-5 reproduction — dose-response vs acceptance band**

# Fig-5 reproduction — dose-response vs acceptance band
_save_viz('repro-fig5-viral-load', 'Fig-5_reproduction_dose-response_vs_acceptance_band', _render_one('local:InfluenzaReproFig5', {}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | repro_fig5 sweeps viral loads and returns a well-formed by_load/band_eval dict with the monotone dose-response | kind=repro_fig5_wellformed_and_monotone_dose_response condition=repro-fig5-reduced-scale stat=final | op eq value True |

# ## Study: Reproduction — Fig 7 (infection-fraction sweep) (`repro-fig7-infection-fraction`)
#
# **Question.** Does `run.repro_fig7` (Task 9.4) correctly sweep `run.run_full_model`
# (Task 9.1) over Sego-2022 Fig-7's initial-infection-fraction scenarios,
# evaluate EACH fraction against ONLY that fraction's own fig7.json band
# subset (never the unfiltered, multi-scenario list, via the shared
# scenario-grouping guard generalized from `repro_fig5`), and reproduce the
# paper's central threshold-like severity-response direction -- and,
# honestly, does a REDUCED-scale sweep (the only scale a fast CI test can
# run) show that direction even though it cannot match the digitized bands'
# absolute magnitudes at paper scale, and does it surface any NEW
# reduced-scale artifacts beyond what `repro_fig5`/`repro_fig3b` already
# documented?
#
# **Objective.** Implement `run.repro_fig7(*, fracs=(0.001,0.005,0.01,0.05), replicas=3,
# cells_per_side=35, steps=240, seed0=0) -> dict` (Task 9.4): for each
# `frac`, loop `replicas` seeds through `run.run_full_model(
# cells_per_side=cells_per_side, steps=steps, seed=seed0+frac_idx*replicas+r,
# init_infection_frac=frac, init_viral_load=None)`; map each run's
# `counts`/`fields`/`ode` sections onto `targets/fig7.json`'s exact 4
# observable keys (reusing `_FIG5_OBSERVABLE_MAP`); ensemble-mean via
# `bands.aggregate_replicas`; filter that fraction's own band subset from
# fig7.json's multi-scenario observable lists (`_fig7_target_subset`,
# raising `ValueError` rather than silently mixing scenarios if a fraction
# has no matching entries); evaluate via `_evaluate_fig7_subset`. Add
# `tests/test_influenza_full_model.py::
# test_repro_fig7_infection_fraction_sweep` (reduced:
# `fracs=(0.001,0.05), replicas=1, cells_per_side=12, steps=15`) asserting
# the by_frac dict has exactly the tested fractions as keys, the monotone
# dose-response holds (`uninfected_final_frac(0.05) <=
# uninfected_final_frac(0.001) + 1e-9`), and `band_eval` is present -- NOT
# that the bands pass. ALSO add
# `test_fig7_target_subset_scenario_grouping_guard`, a fast unit test
# directly exercising `_fig7_target_subset`'s filter (returns only the
# matching-tag entries) and its raise (unmatched fraction), closing the
# Task-9.3-review-flagged gap that the guard was previously verified only
# interactively. Run the reduced config directly (not the pytest assertions
# alone) to report the actual per-fraction, per-observable band_eval numbers
# in this study honestly.
#
# **Hypothesis.** `run.repro_fig7` correctly wires the per-fraction ensemble-and-scenario-
# filtered-band-evaluation machinery, reusing `repro_fig5`'s shared
# `_scenario_target_subset` guard rather than duplicating it: for each
# tested fraction it runs `replicas` seeded `run_full_model` calls with
# `round(frac*tot_cell)` pre-infected cells, maps every observable onto
# fig7's keys, ensemble-means them, filters fig7.json's observable lists
# down to that fraction's own scenario subset (the guard), and produces a
# well-formed per-fraction `band_eval`. At REDUCED scale (few fractions/
# replicas, a small population, a short duration -- all needed to keep the
# added pytest test fast), the ensemble is NOT expected to land in-band
# against bands digitized from a 10000-cell, 20-replica, 15-day paper-scale
# ensemble, but the MONOTONE dose-response direction (higher initial
# infection fraction -> not-more surviving uninfected fraction) should
# still hold. A risk specific to `init_infection_frac` (unlike fig5's
# `init_viral_load`, which has no analogous rounding step): the smallest
# fraction may round to zero seeded cells at a small `cells_per_side`,
# producing a degenerate no-infection run that should be reported as what
# it is, not oversold as reproduction evidence.
#
# **Purpose.** full_model_infection_fraction_sweep_vs_fig7_acceptance_bands
#
# **Claim.** `repro_fig7` is wired correctly: it sweeps a seeded ensemble of the full
# model across Fig-7's infection-fraction scenarios and evaluates each
# fraction against only its own acceptance-band subset. Fig-7 is not
# reproduced at reduced scale — per-fraction band containment fails, and
# the smallest tested fraction degenerates to a no-infection control since
# it rounds to zero seeded cells. The monotone dose-response direction
# still holds; a paper-scale ensemble is required before reproduction.

# ### Parameters
#
# | simulation | composite | steps | params |
# | --- | --- | --- | --- |
# | `baseline` | `viva_cpm_studies.composites.influenza.full_model` | 15 | fracs=[0.001, 0.05], replicas=1, cells_per_side=12, seed0=0 |

# ### Specification (process-bigraph) — load, inspect, edit
#
# Each composite is a process-bigraph *document*: named processes (`_type: process`) bound to an `address`, wired by `inputs`/`outputs` ports over shared stores. For every composite below the first cell loads the spec into a plain **editable Python dict** and prints its structure; the second cell is a **control panel** listing every configuration value and per-process `interval` so you can tweak any of them. Your edits are read when the composite is built and run, in the **Run** section.

# **Composite `viva_cpm_studies.composites.influenza.full_model`** — `spec_viva_cpm_studies_composites_influenza_full_model` (a plain, editable dict)

# _composite spec file for `viva_cpm_studies.composites.influenza.full_model` not found under `viva_cpm_studies/composites/` — skipped._

# ### Run
#
# _Set the runtime (`STEPS`) and step size (`INTERVAL`), then run. Each simulation builds the (edited) spec above and writes `runs.db`; the figures below read it. Set `RERUN = False` to skip re-simulating._

# === Study: repro-fig7-infection-fraction ===
STUDY = 'repro-fig7-infection-fraction'
STUDY_DIR = REPO / 'workspace/studies' / STUDY
STUDY_YAML = str(STUDY_DIR / "study.yaml")
RUNS_DB = str(STUDY_DIR / "runs.db")

print("No recorded runs for this study; nothing to reproduce.")

# ### Visualizations
#
# _Results are shown by the figures below, produced by the run above._

# **Spatial state — full model (animated)**

# Spatial state — full model (animated)
_save_viz('repro-fig7-infection-fraction', 'Spatial_state_full_model_animated', _render_one('local:InfluenzaSpatialReproFig7', {}, RUNS_DB, STUDY_YAML))

# **Fig-7 reproduction — dose-response vs acceptance band**

# Fig-7 reproduction — dose-response vs acceptance band
_save_viz('repro-fig7-infection-fraction', 'Fig-7_reproduction_dose-response_vs_acceptance_band', _render_one('local:InfluenzaReproFig7', {}, RUNS_DB, STUDY_YAML))

# ### Acceptance criteria
#
# _Pre-registered checks (criteria/thresholds only — run the cells above to evaluate them)._
#
# | test | measures | passes if |
# | --- | --- | --- |
# | repro_fig7 sweeps infection fractions and returns a well-formed by_frac/band_eval dict with the monotone dose-response | kind=repro_fig7_wellformed_and_monotone_dose_response condition=repro-fig7-reduced-scale stat=final | op eq value True |
# | Scenario-grouping guard filters fig7's tagged observables correctly and raises loudly on an unmatched fraction | kind=fig7_scenario_grouping_guard_filter_and_raise condition=repro-fig7-reduced-scale stat=final | op eq value True |

# ## Open decisions
# - Should any of the eight source-versus-paper discrepancies be resolved toward the paper's stated values instead of the source-literal ones, before the parameter file locks in as ground truth for the rest of the investigation?
